name: projeto_atividade
description: Aplicativo para leitura.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

  # System
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  ios_utsname_ext: ^2.2.0

  # UUID
  uuid: ^4.4.0

  # Crypto
  crypto: ^3.0.2

  # Database
  floor: ^1.4.1
  flutter_secure_storage: ^9.0.0

  # Network
  dio: ^5.1.1
  dio_http2_adapter: ^2.4.0
  retrofit: ^4.0.1
  http_parser: ^4.0.2
  json_annotation: ^4.8.1
  connectivity_plus: ^6.0.3

  # Login
  flutter_login: ^5.0.0

  # Path
  path: ^1.8.2
  path_provider: ^2.0.14

  # Camera
  camera: ^0.11.0+1

  # PhotoView
  photo_view: ^0.15.0

  # EasyLoading
  flutter_easyloading: ^3.0.5

  # DateField
  date_field: ^5.0.1

  # Dropdown
  dropdown_search: ^5.0.6

  # Geolocation
  geolocator: ^12.0.0

  # Image
  image: ^4.0.15

  flutter_treeview: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

  build_runner: ^2.3.3
  floor_generator: ^1.4.1
  retrofit_generator: ^9.1.3
  json_serializable: ^6.6.1

  flutter_launcher_icons: ^0.14.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  # Localizations
  generate: true

  assets:
    - assets/images/
    - assets/icon/asset.png
    - assets/icon/component.png
    - assets/icon/location.png

flutter_launcher_icons:
  image_path: 'assets/icon/icon.png'
  android: 'ic_launcher'
  ios: true
  min_sdk_android: 21
